altTranslationKeyFormat: null
altTranslationMethod: language
fieldLayouts:
  f454fc49-d266-4120-8b9f-37fab45417f9:
    cardView:
      - 'layoutElement:b8920e32-b702-4cd5-98d9-dddc5f73b319'
      - 'layoutElement:0c7b4523-d11f-4497-8478-13d49872b771'
      - imageSize
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-26T15:02:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 385fd96a-acde-4a98-b47f-0e077cbb61c8
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-03-26T15:06:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: true
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: true
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: b8920e32-b702-4cd5-98d9-dddc5f73b319
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-01T08:18:12+00:00'
            elementCondition: null
            fieldUid: b955f048-a606-4550-b6e7-6ebc117db7b1 # Copyright
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c7b4523-d11f-4497-8478-13d49872b771
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66c440bd-d7c0-4c81-9cd4-e99b9b404dfb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-01T10:54:46+00:00'
            elementCondition: null
            template: _cp/related-entries.twig
            templateMode: site
            type: craft\fieldlayoutelements\Template
            uid: 59b13985-b5d3-4870-a9db-08f54d0214f7
            userCondition: null
            width: 100
        name: Relationships
        uid: 7fccc13a-c9cb-447b-b804-744aaac6c4f5
        userCondition: null
fs: $FILES_FS
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: language
transformFs: $TRANSFORM_FS
transformSubpath: images
